TestWeb/Models/Security.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TestWeb.Models
{
    public class Security
    {
        [DisplayName("Login")]
        [Required(ErrorMessage ="Не указан логин")]
        public string Login { get; set; }
        
        [DisplayName("Password")]
        [Required(ErrorMessage = "Не указан пароль")]
        [StringLength(1000, MinimumLength =3, ErrorMessage = "Длина пароля не может быть меньше 3 символов")]
        [Compare("Login", ErrorMessage ="Пароль не может совпадать с логином")]
        public string Password { get; set; }
    }
}

TestWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestWeb.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        //[HttpGet]
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to admin parth";

            return View();
        }

    }
}

TestWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewData["Test1"] = "1111";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TestWeb/Controllers/SecurityController.cs
using System.Web.Mvc;
using TestWeb.Models;

namespace TestWeb.Controllers
{
    public class SecurityController : Controller
    {
        // GET: Security
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string Login, string Password)
        {
            if (!ModelState.IsValid) return View("Index");

            var security = new Security() 
            { Login = Login,
              Password = Password };

            return View("Result", security); 
        }


        [HttpPost]
        [ActionName("Submit")]
        public ActionResult Result()
        {
            return View("Result", new Security() { Login = "1", Password = "10" }) ;
        }

    }
}

TestWeb/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin</h2>

TestWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
    <div>
        @ViewBag.Test
        <br />
        @ViewData["Test1"]
    </div>
</div>

TestWeb/Views/Security/Index.cshtml
@model TestWeb.Models.Security
@Html.ValidationSummary()

@using (Html.BeginForm("Index", "Security", FormMethod.Post))
{
    @Html.ValidationSummary()

    <h3> Input you login and password</h3>
    <fieldset>
        <div class="mb-3, editor-field">
            @Html.LabelFor(p => p.Login)
            <br />
            <input type="text" class="form-control" name="Login" id="Login" autofocus required />
            
            @*@Html.EditorFor(p => p.Login)*@
            @*@Html.ValidationMessageFor(p => p.Login)*@
        </div>
        <div class="mb-3, editor-field">
            @Html.LabelFor(p => p.Password)
            <br />
            <input type="password" class="form-control" name="Password" id="Password" required>
            <span asp-validation-for="Password"></span>
            @*@Html.PasswordFor(p => p.Password)*@
            @*@Html.ValidationMessageFor(p => p.Password)*@
        </div>
        <button type="submit" class="btn btn-primary" name="Submit">Submit</button>
    </fieldset>
}
@{Html.EndForm();}

@section scripts{

    }

TestWeb/Views/Security/Result.cshtml
@model TestWeb.Models.Security

@{
    ViewBag.Title = "Result";

}
@using (Html.BeginForm("Result", "Security", FormMethod.Post))
{
    @Html.ValidationSummary()

    <h3>You input: </h3>
    <div class="mb-3, editor-field">
        @Html.LabelFor(p => p.Login)
        <br />
        @Html.TextBoxFor(p => p.Login, new { @readonly = "readonly" })
        @Html.ValidationMessageFor(p => p.Login)
    </div>
    <div class="mb-3, editor-field">
        @Html.LabelFor(p => p.Password)
        <br />
        @Html.TextBoxFor(p => p.Password, new { @readonly = "readonly" })
    </div>
}

TestWeb/Views/Shared/_Footer.cshtml
<div>
    Это текст из частичного представления.
    <br />
    @Html.ActionLink("Ссылка на метод действия Index", "Index", "Home")
</div>
<div>
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
</div>

TestWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Security", "Index", "Security")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("_Footer")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>